//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProMeetProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public int Vendor_Id { get; set; }
        public string name { get; set; }
        public string Email_id { get; set; }
        public double phone { get; set; }
        public string address { get; set; }
        public string password { get; set; }
        public bool IsEmailVerified { get; set; }
        public System.Guid ActivationCode { get; set; }
        public string ResetPasswordCode { get; set; }
    }
}
